<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-Q37MKND" ignored="0" name="APITEST" tests="3" failures="2" timestamp="11 一月 2019 07:43:45 GMT" time="24.326" errors="0">
  <testcase name="postVehiclesForStatus" time="2.166" classname="com.bitnei.apitest.testcases.PostVehicles"/>
  <testcase name="PostVehiclesByVin" time="2.456" classname="com.bitnei.apitest.testcases.PostVehicles">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&amp;quot;status&amp;quot;:{&amp;quot;currentValue is &amp;quot;:200,&amp;quot;expectedValue is&amp;quot;:20},&amp;quot;total&amp;quot;:{&amp;quot;currentValue is &amp;quot;:0,&amp;quot;expectedValue is&amp;quot;:2},&amp;quot;Length&amp;quot;:{&amp;quot;actualLenth&amp;quot;:0,&amp;quot;expectLenth&amp;quot;:1},&amp;quot;error&amp;quot;:{&amp;quot;currentValue is &amp;quot;:false,&amp;quot;expectedValue is&amp;quot;:true}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"status":{"currentValue is ":200,"expectedValue is":20},"total":{"currentValue is ":0,"expectedValue is":2},"Length":{"actualLenth":0,"expectLenth":1},"error":{"currentValue is ":false,"expectedValue is":true}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.PostVehicles.PostVehiclesByVin(PostVehicles.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- PostVehiclesByVin -->
  <testcase name="getVehCountPerMonitorPlatformStatus" time="21.019" classname="com.bitnei.apitest.testcases.getVehCountPerMonitorPlatform">
    <failure type="org.apache.http.conn.HttpHostConnectException" message="Connect to bdp-app.bitnei.cn:80 [bdp-app.bitnei.cn/123.58.16.222] failed: Connection timed out: connect">
      <![CDATA[org.apache.http.conn.HttpHostConnectException: Connect to bdp-app.bitnei.cn:80 [bdp-app.bitnei.cn/123.58.16.222] failed: Connection timed out: connect
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
at com.bitnei.apitest.utils.RestClient.get(RestClient.java:38)
at com.bitnei.apitest.testcases.getVehCountPerMonitorPlatform.getVehCountPerMonitorPlatformStatus(getVehCountPerMonitorPlatform.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
at java.net.DualStackPlainSocketImpl.connect0(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
at java.net.PlainSocketImpl.connect(Unknown Source)
at java.net.SocksSocketImpl.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
... 24 more
]]>
    </failure>
  </testcase> <!-- getVehCountPerMonitorPlatformStatus -->
</testsuite> <!-- APITEST -->
