<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-Q37MKND" ignored="0" name="APITEST" tests="19" failures="6" timestamp="22 二月 2019 09:55:58 GMT" time="17.836" errors="0">
  <testcase name="postVehiclesForStatus" time="0.813" classname="com.bitnei.apitest.testcases.PostVehicles"/>
  <testcase name="PlatFormAdd" time="0.511" classname="com.bitnei.apitest.testcases.datasend.PlatFormSelect"/>
  <testcase name="PlatFormAdd" time="0.141" classname="com.bitnei.apitest.testcases.datasend.PlatForm"/>
  <testcase name="ProtocolAddData" time="0.234" classname="com.bitnei.apitest.testcases.datasend.ProtocolAdd"/>
  <testcase name="ProtocolUpdateData" time="3.796" classname="com.bitnei.apitest.testcases.datasend.ProtocolUpdate"/>
  <testcase name="TaskAddData" time="0.097" classname="com.bitnei.apitest.testcases.datasend.TaskAdd">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&amp;quot;status&amp;quot;:{&amp;quot;currentValue is &amp;quot;:500,&amp;quot;expectedValue is&amp;quot;:200},&amp;quot;error&amp;quot;:{&amp;quot;currentValue is &amp;quot;:true,&amp;quot;expectedValue is&amp;quot;:false}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"status":{"currentValue is ":500,"expectedValue is":200},"error":{"currentValue is ":true,"expectedValue is":false}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.datasend.TaskAdd.TaskAddData(TaskAdd.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- TaskAddData -->
  <testcase name="ForwardVehicleByVin" time="0.838" classname="com.bitnei.apitest.testcases.datasend.ForwardVehicleQuery"/>
  <testcase name="ForwardVehicleSelect" time="1.184" classname="com.bitnei.apitest.testcases.datasend.ForwardVehicleSelectVehicles">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&amp;quot;id&amp;quot;:{&amp;quot;currentValue is &amp;quot;:786457,&amp;quot;expectedValue&amp;quot;:&amp;quot;786457&amp;quot;},&amp;quot;communicationProtocol&amp;quot;:{&amp;quot;currentValue is &amp;quot;:786457,&amp;quot;expectedValue&amp;quot;:&amp;quot;786457&amp;quot;,&amp;quot;actualKey&amp;quot;:&amp;quot;不存在此communicationProtocol&amp;quot;,&amp;quot;expectedKey&amp;quot;:&amp;quot;communicationProtocol&amp;quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"id":{"currentValue is ":786457,"expectedValue":"786457"},"communicationProtocol":{"currentValue is ":786457,"expectedValue":"786457","actualKey":"不存在此communicationProtocol","expectedKey":"communicationProtocol"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.datasend.ForwardVehicleSelectVehicles.ForwardVehicleSelect(ForwardVehicleSelectVehicles.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- ForwardVehicleSelect -->
  <testcase name="ForwardVehicleAddVehicles" time="0.092" classname="com.bitnei.apitest.testcases.datasend.ForwardVehicleAddVehicle"/>
  <testcase name="ForwardVehicleRemoveVehicles" time="0.129" classname="com.bitnei.apitest.testcases.datasend.ForwardVehicleRemoveVehicle"/>
  <testcase name="getVehCountPerMonitorPlatformStatus" time="0.62" classname="com.bitnei.apitest.testcases.getVehCountPerMonitorPlatform">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&amp;quot;num&amp;quot;:{&amp;quot;currentValue is &amp;quot;:274421,&amp;quot;expectedValue is&amp;quot;:274419}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"num":{"currentValue is ":274421,"expectedValue is":274419}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.getVehCountPerMonitorPlatform.getVehCountPerMonitorPlatformStatus(getVehCountPerMonitorPlatform.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getVehCountPerMonitorPlatformStatus -->
  <testcase name="getVehCountPerMonitorPlatformStatus" time="0.872" classname="com.bitnei.apitest.testcases.EvDetail"/>
  <testcase name="PlatFormModify" time="0.803" classname="com.bitnei.apitest.testcases.datasend.PlatFormUpdate"/>
  <testcase name="PlatFormDelData" time="0.602" classname="com.bitnei.apitest.testcases.datasend.PlatFormDel"/>
  <testcase name="ProtocolDeleteData" time="0.629" classname="com.bitnei.apitest.testcases.datasend.ProtocolDelete"/>
  <testcase name="TaskAddDataRep" time="0.092" classname="com.bitnei.apitest.testcases.datasend.TaskAdd">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&amp;quot;errorMsg&amp;quot;:{&amp;quot;currentValue is &amp;quot;:&amp;quot;请分配租户&amp;quot;,&amp;quot;expectedValue&amp;quot;:&amp;quot;该平台已分配，不能重复添加&amp;quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"errorMsg":{"currentValue is ":"请分配租户","expectedValue":"该平台已分配，不能重复添加"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.datasend.TaskAdd.TaskAddDataRep(TaskAdd.java:116)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- TaskAddDataRep -->
  <testcase name="ForwardVehicleBylicense" time="0.622" classname="com.bitnei.apitest.testcases.datasend.ForwardVehicleQuery"/>
  <testcase name="TaskAddDataRepTask" time="0.054" classname="com.bitnei.apitest.testcases.datasend.TaskAdd">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&amp;quot;errorMsg&amp;quot;:{&amp;quot;currentValue is &amp;quot;:&amp;quot;请分配租户&amp;quot;,&amp;quot;expectedValue&amp;quot;:&amp;quot;任务名称已存在&amp;quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"errorMsg":{"currentValue is ":"请分配租户","expectedValue":"任务名称已存在"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.datasend.TaskAdd.TaskAddDataRepTask(TaskAdd.java:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- TaskAddDataRepTask -->
  <testcase name="TaskDeleteData" time="0.549" classname="com.bitnei.apitest.testcases.datasend.TaskDelete">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:657)
at java.util.ArrayList.get(ArrayList.java:433)
at com.bitnei.apitest.testcases.datasend.TaskDelete.TaskDeleteData(TaskDelete.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- TaskDeleteData -->
</testsuite> <!-- APITEST -->
