<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-Q37MKND" name="com.bitnei.apitest.testcases.openapi.ChargingDataTest" tests="2" failures="0" timestamp="28 五月 2019 03:54:30 GMT" time="1.334" errors="1">
  <testcase name="setUp" time="1.334" classname="com.bitnei.apitest.testcases.openapi.ChargingDataTest">
    <error type="net.sf.json.JSONException" message="JSONObject[&quot;access_token&quot;] not found.">
      <![CDATA[net.sf.json.JSONException: JSONObject["access_token"] not found.
at net.sf.json.JSONObject.getString(JSONObject.java:2092)
at com.bitnei.apitest.testcases.openapi.OauthToken.GetOauthToken(OauthToken.java:40)
at com.bitnei.apitest.testcases.openapi.ChargingDataTest.setUp(ChargingDataTest.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase name="ChargingDataNormal" time="0.000" classname="com.bitnei.apitest.testcases.openapi.ChargingDataTest">
    <skipped/>
  </testcase> <!-- ChargingDataNormal -->
</testsuite> <!-- com.bitnei.apitest.testcases.openapi.ChargingDataTest -->
