<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-Q37MKND" name="com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel" tests="7" failures="1" timestamp="27 九月 2019 08:52:56 GMT" time="5.960" errors="0">
  <testcase name="UserInfoQueryData" time="0.429" classname="com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel"/>
  <testcase name="UserInfoQueryData" time="1.068" classname="com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel"/>
  <testcase name="UserInfoQueryData" time="1.019" classname="com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel"/>
  <testcase name="UserInfoQueryData" time="0.649" classname="com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&quot;errorMsg&quot;:{&quot;currentValue is &quot;:&quot;str:用户hangang@bitnei.cn已经存在&quot;,&quot;expectedValue is &quot;:&quot;NORMAL&quot;},&quot;data&quot;:{&quot;currentValue is &quot;:null,&quot;expectedValue is &quot;:&quot;用户hangang@bitnei.cn已经存在&quot;,&quot;actualValue&quot;:null,&quot;expectedValue&quot;:&quot;用户hangang@bitnei.cn已经存在&quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"errorMsg":{"currentValue is ":"str:用户hangang@bitnei.cn已经存在","expectedValue is ":"NORMAL"},"data":{"currentValue is ":null,"expectedValue is ":"用户hangang@bitnei.cn已经存在","actualValue":null,"expectedValue":"用户hangang@bitnei.cn已经存在"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel.UserInfoQueryData(UserInfoQueryByExcel.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- UserInfoQueryData -->
  <testcase name="UserInfoQueryData" time="1.729" classname="com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel"/>
  <testcase name="UserInfoQueryData" time="0.550" classname="com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel"/>
  <testcase name="UserInfoQueryData" time="0.516" classname="com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel"/>
</testsuite> <!-- com.bitnei.apitest.testcases.saas.UserInfoQueryByExcel -->
