<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-Q37MKND" name="com.bitnei.apitest.testcases.saas.ApiTest" tests="11" failures="6" timestamp="11 二月 2020 08:25:51 GMT" time="1.306" errors="0">
  <testcase name="ApiTestCode" time="0.346" classname="com.bitnei.apitest.testcases.saas.ApiTest"/>
  <testcase name="ApiTestCode" time="0.062" classname="com.bitnei.apitest.testcases.saas.ApiTest"/>
  <testcase name="ApiTestCode" time="0.159" classname="com.bitnei.apitest.testcases.saas.ApiTest">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&quot;error&quot;:{&quot;currentValue is &quot;:true,&quot;expectedValue is&quot;:false},&quot;code&quot;:{&quot;currentValue is &quot;:&quot;40000&quot;,&quot;expectedValue is&quot;:false,&quot;expectedValue is &quot;:&quot;10000&quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"error":{"currentValue is ":true,"expectedValue is":false},"code":{"currentValue is ":"40000","expectedValue is":false,"expectedValue is ":"10000"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.saas.ApiTest.ApiTestCode(ApiTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- ApiTestCode -->
  <testcase name="ApiTestCode" time="0.068" classname="com.bitnei.apitest.testcases.saas.ApiTest"/>
  <testcase name="ApiTestCode" time="0.038" classname="com.bitnei.apitest.testcases.saas.ApiTest">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&quot;error&quot;:{&quot;currentValue is &quot;:true,&quot;expectedValue is&quot;:false},&quot;code&quot;:{&quot;currentValue is &quot;:&quot;40000&quot;,&quot;expectedValue is&quot;:false,&quot;expectedValue is &quot;:&quot;10000&quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"error":{"currentValue is ":true,"expectedValue is":false},"code":{"currentValue is ":"40000","expectedValue is":false,"expectedValue is ":"10000"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.saas.ApiTest.ApiTestCode(ApiTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- ApiTestCode -->
  <testcase name="ApiTestCode" time="0.053" classname="com.bitnei.apitest.testcases.saas.ApiTest">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&quot;error&quot;:{&quot;currentValue is &quot;:true,&quot;expectedValue is&quot;:false},&quot;code&quot;:{&quot;currentValue is &quot;:&quot;40000&quot;,&quot;expectedValue is&quot;:false,&quot;expectedValue is &quot;:&quot;10000&quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"error":{"currentValue is ":true,"expectedValue is":false},"code":{"currentValue is ":"40000","expectedValue is":false,"expectedValue is ":"10000"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.saas.ApiTest.ApiTestCode(ApiTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- ApiTestCode -->
  <testcase name="ApiTestCode" time="0.108" classname="com.bitnei.apitest.testcases.saas.ApiTest">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&quot;error&quot;:{&quot;currentValue is &quot;:true,&quot;expectedValue is&quot;:false},&quot;code&quot;:{&quot;currentValue is &quot;:&quot;40000&quot;,&quot;expectedValue is&quot;:false,&quot;expectedValue is &quot;:&quot;10000&quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"error":{"currentValue is ":true,"expectedValue is":false},"code":{"currentValue is ":"40000","expectedValue is":false,"expectedValue is ":"10000"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.saas.ApiTest.ApiTestCode(ApiTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- ApiTestCode -->
  <testcase name="ApiTestCode" time="0.082" classname="com.bitnei.apitest.testcases.saas.ApiTest">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&quot;error&quot;:{&quot;currentValue is &quot;:true,&quot;expectedValue is&quot;:false},&quot;code&quot;:{&quot;currentValue is &quot;:&quot;40000&quot;,&quot;expectedValue is&quot;:false,&quot;expectedValue is &quot;:&quot;35000&quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"error":{"currentValue is ":true,"expectedValue is":false},"code":{"currentValue is ":"40000","expectedValue is":false,"expectedValue is ":"35000"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.saas.ApiTest.ApiTestCode(ApiTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- ApiTestCode -->
  <testcase name="ApiTestCode" time="0.038" classname="com.bitnei.apitest.testcases.saas.ApiTest">
    <failure type="java.lang.AssertionError" message="expected [{}] but found [{&quot;data&quot;:{&quot;actualValue&quot;:null,&quot;expectedValue&quot;:{&quot;risk_score&quot;:null,&quot;mileage_12&quot;:null,&quot;mileage_24&quot;:null,&quot;mileage_36&quot;:null}},&quot;risk_score&quot;:{&quot;actualKey&quot;:&quot;不存在此risk_score&quot;,&quot;expectedKey&quot;:&quot;risk_score&quot;},&quot;mileage_12&quot;:{&quot;actualKey&quot;:&quot;不存在此mileage_12&quot;,&quot;expectedKey&quot;:&quot;mileage_12&quot;},&quot;mileage_24&quot;:{&quot;actualKey&quot;:&quot;不存在此mileage_24&quot;,&quot;expectedKey&quot;:&quot;mileage_24&quot;},&quot;mileage_36&quot;:{&quot;actualKey&quot;:&quot;不存在此mileage_36&quot;,&quot;expectedKey&quot;:&quot;mileage_36&quot;},&quot;error&quot;:{&quot;actualValue&quot;:null,&quot;expectedValue&quot;:{&quot;risk_score&quot;:null,&quot;mileage_12&quot;:null,&quot;mileage_24&quot;:null,&quot;mileage_36&quot;:null},&quot;currentValue is &quot;:true,&quot;expectedValue is&quot;:false},&quot;code&quot;:{&quot;actualValue&quot;:null,&quot;expectedValue&quot;:{&quot;risk_score&quot;:null,&quot;mileage_12&quot;:null,&quot;mileage_24&quot;:null,&quot;mileage_36&quot;:null},&quot;currentValue is &quot;:&quot;40000&quot;,&quot;expectedValue is&quot;:false,&quot;expectedValue is &quot;:&quot;10000&quot;}}]">
      <![CDATA[java.lang.AssertionError: expected [{}] but found [{"data":{"actualValue":null,"expectedValue":{"risk_score":null,"mileage_12":null,"mileage_24":null,"mileage_36":null}},"risk_score":{"actualKey":"不存在此risk_score","expectedKey":"risk_score"},"mileage_12":{"actualKey":"不存在此mileage_12","expectedKey":"mileage_12"},"mileage_24":{"actualKey":"不存在此mileage_24","expectedKey":"mileage_24"},"mileage_36":{"actualKey":"不存在此mileage_36","expectedKey":"mileage_36"},"error":{"actualValue":null,"expectedValue":{"risk_score":null,"mileage_12":null,"mileage_24":null,"mileage_36":null},"currentValue is ":true,"expectedValue is":false},"code":{"actualValue":null,"expectedValue":{"risk_score":null,"mileage_12":null,"mileage_24":null,"mileage_36":null},"currentValue is ":"40000","expectedValue is":false,"expectedValue is ":"10000"}}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.bitnei.apitest.testcases.saas.ApiTest.ApiTestCode(ApiTest.java:101)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- ApiTestCode -->
  <testcase name="ApiTestCode" time="0.077" classname="com.bitnei.apitest.testcases.saas.ApiTest"/>
  <testcase name="ApiTestCode" time="0.275" classname="com.bitnei.apitest.testcases.saas.ApiTest"/>
</testsuite> <!-- com.bitnei.apitest.testcases.saas.ApiTest -->
